Fix issue when composer.json file is not in root directory
wunderio/code-quality-old pull request #15
Opened 2019-08-09 08:43 UTC by mgalang

2019-08-09 08:52 UTC, ragnarkurmwunder requested changes

2019-08-09 08:52 UTC, ragnarkurmwunder commented on install-update.sh
> +  cp "$src" "$dst"
If you copy the file, then we are losing reference to the package.

2019-08-09 08:52 UTC, ragnarkurmwunder commented on install-update.sh
> +  cp "$src" "$dst"
The link allows us to trace back or locate the package for lib files.

2019-08-09 11:02 UTC, mgalang commented on install-update.sh
> +  cp "$src" "$dst"
@ragnarkurmwunder This is now fixed. I also improved the we check for git

2019-08-09 11:08 UTC, hkirsman approved these changes

2019-08-09 11:08 UTC, hkirsman commented on install-update.sh
> +  cp "$src" "$dst"
What's happening here. ln to cp?

2019-08-09 11:48 UTC, merged

2019-09-18 16:51 UTC, mgalang commented on src/Task/AbstractLintTask.php
> +    $files = $result = $this->getFilesOrResult($context, $this->getConfiguration(), $this);
Why does this need 2 variable assignments? I think it could be done with just 1?

2019-09-19 06:52 UTC, mgalang commented on src/Task/AbstractMultiPathProcessingTask.php
> +    $files = $result = $this->getFilesOrResult($context, $this->getConfiguration(), $this);
Same here?

2019-09-19 06:57 UTC, mgalang commented on src/Task/AbstractSinglePathProcessingTask.php
> +      $process = $this->processBuilder->buildProcess($this->buildArgumentsFromPath((string) $path));
Can you make this line a bit more readable by explicitly declaring arguments from path as a separate variable above $process?

2019-09-19 06:58 UTC, mgalang commented on src/Task/AbstractSinglePathProcessingTask.php
> +        $output .= PHP_EOL . $this->formatter->format($process);
Use End of line character at the actual end of line? ;)